apache/maven-mvnd

- src/main/distro/bin/mvnd
- src/main/java/org/jboss/fuse/mvnd/daemon/Client.java
Allows for a workaround for https://github.com/gnodet/mvnd/issues/12
> Make --threads and --builder overridable via CLI

- client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
- client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
- client/src/main/java/org/jboss/fuse/mvnd/client/Environment.java
- client/src/main/java/org/jboss/fuse/mvnd/client/ServerMain.java
- client/src/main/resources/org/jboss/fuse/mvnd/client/mvnd.properties.template
- client/src/test/java/org/jboss/fuse/mvnd/client/EnvironmentTest.java
- daemon/src/main/distro/bin/mvnd
- daemon/src/main/distro/conf/logging/logback.xml
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
- daemon/src/main/java/org/jboss/fuse/mvnd/plugin/CliPluginRealmCache.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/InstallDaemonNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/NativeTestClient.java
> Fix #53 Using MAVEN_HOME may clash with other tools

- client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
- daemon/src/main/java/org/jboss/fuse/mvnd/daemon/Server.java
> Cannot re-use daemon with sdkman java 8.0.265.hs-adpt

- .github/workflows/verify.yaml
> Publish new versions via sdkman vendor API

- .github/workflows/automatic-changelog-update.yml
> Added a changelog automatic update gh action

- build/publish-on-sdkman.sh
- client/src/main/java/org/jboss/fuse/mvnd/client/ClientLayout.java
- common/src/main/java/org/jboss/fuse/mvnd/common/Layout.java
- common/src/main/java/org/jboss/fuse/mvnd/common/ServerMain.java
- daemon/pom.xml
- daemon/src/main/java/org/jboss/fuse/mvnd/daemon/Server.java
- daemon/src/main/provisio/maven-distro.xml
- daemon/src/test/java/org/jboss/fuse/mvnd/dist/DistroIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/ModuleAndPluginNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/UpgradesInBomNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/UpgradesInBomTest.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/ClientFactory.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/MvndTestExtension.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/TestRegistry.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/TestUtils.java
- integration-tests/src/test/projects/module-and-plugin/pom.xml
- integration-tests/src/test/projects/multi-module/pom.xml
- integration-tests/src/test/projects/upgrades-in-bom/hello-0.0.1/pom.xml
- integration-tests/src/test/projects/upgrades-in-bom/hello-0.0.1/src/main/java/org/jboss/fuse/mvnd/test/upgrades/bom/hello/Hello.java
- integration-tests/src/test/projects/upgrades-in-bom/hello-0.0.2-SNAPSHOT/pom.xml
- integration-tests/src/test/projects/upgrades-in-bom/hello-0.0.2-SNAPSHOT/src/main/java/org/jboss/fuse/mvnd/test/upgrades/bom/hello/Hello.java
- integration-tests/src/test/projects/upgrades-in-bom/parent/bom/pom.xml
- integration-tests/src/test/projects/upgrades-in-bom/parent/module/pom.xml
- integration-tests/src/test/projects/upgrades-in-bom/parent/module/src/main/java/org/jboss/fuse/mvnd/test/upgrades/bom/module/UseHello.java
- integration-tests/src/test/projects/upgrades-in-bom/parent/pom.xml
>  CachingProjectBuilder ignored

- .mvn/extensions.xml
- integration-tests/pom.xml
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/ModuleAndPluginNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/MultiModuleTest.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/SingleModuleNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/MvndTestExtension.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/NativeTestClient.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/TestUtils.java
- integration-tests/src/test/resources/settings-template.xml
> Use a maven proxy for integration tests to speed them up

- daemon/src/main/distro/bin/mvn.cmd
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/InvokerNativeIT.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/InvokerTest.java
- integration-tests/src/test/projects/invoker/pom.xml
- integration-tests/src/test/projects/invoker/src/it/invoke-hello/invoker.properties
- integration-tests/src/test/projects/invoker/src/it/invoke-hello/pom.xml
- integration-tests/src/test/projects/invoker/src/it/invoke-hello/verify.groovy
- integration-tests/src/test/projects/invoker/src/main/java/org/jboss/fuse/mvnd/test/invoker/hello/HelloMojo.java
> Test a scenario using mvn #92

- .github/workflows/update-changelog.yml
- .github/workflows/verify.yaml
> Replace deprecated GitHub actions commands #85

- client/pom.xml
- client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
- client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
- client/src/test/java/org/jboss/fuse/mvnd/client/OsUtilsTest.java
- common/src/main/java/org/jboss/fuse/mvnd/common/Os.java
- common/src/main/java/org/jboss/fuse/mvnd/common/OsUtils.java
- common/src/test/java/org/jboss/fuse/mvnd/common/OsUtilsTest.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/NativeTestClient.java
> mvnd --status to display memory usage #129

- common/src/main/java/org/jboss/fuse/mvnd/common/OsUtils.java
> mvnd --status throws NumberFormatException in 0.0.9

- client/pom.xml
- client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
- integration-tests/src/test/java/org/jboss/fuse/mvnd/it/ModuleAndPluginNativeIT.java
- integration-tests/src/test/projects/module-and-plugin/plugin/src/main/java/org/jboss/fuse/mvnd/test/module/plugin/mojo/HelloMojo.java
> mvnd native executable is not passing -Dkey=val to the daemon

- client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
- common/src/main/java/org/jboss/fuse/mvnd/common/Environment.java
> ProjectBuildLogAppender not found when starting the daemon #165

- client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
- common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
> mvn -Dmvnd.noBuffering=true has no effect 

- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
> mvnd --help produces no output #238

- daemon/src/main/java/org/mvndaemon/mvnd/builder/SmartBuilder.java
- pom.xml
> Deprecate mvnd.builder.rule* and mvnd.builder.rules.provider.* features

- client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
- client/src/test/java/org/mvndaemon/mvnd/client/EnvironmentTest.java
- common/src/main/java/org/mvndaemon/mvnd/common/OptionType.java
- integration-tests/pom.xml
- integration-tests/src/test/java/org/mvndaemon/mvnd/junit/MvndTestExtension.java
- pom.xml
> Support short variants of boolean properties

- README.adoc
> Document how to install bash completion

- daemon/src/main/java/org/mvndaemon/mvnd/builder/DependencyGraph.java
- daemon/src/test/java/org/mvndaemon/mvnd/builder/DagWidthTest.java
- integration-tests/pom.xml
- integration-tests/src/test/java/org/mvndaemon/mvnd/junit/MvndTestExtension.java
- pom.xml
A test case for a bug in DagWidth
> DAG width wrong for parent runtime deployment triple

- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
> The output of ConsoleMavenTransferListener looks ugly in the client 

- common/src/main/java/org/mvndaemon/mvnd/common/Message.java
- common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
- daemon/src/main/java/org/mvndaemon/mvnd/daemon/ClientDispatcher.java
- daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
- daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/BuildEventListener.java
- daemon/src/main/java/org/mvndaemon/mvnd/transfer/DaemonMavenTransferListener.java
This is a first pass at a better display of download events on the client.
@ppalaga could you give it a try see how it can be improved ?
> Send transfer events to the client for better display, #284

- integration-tests/src/test/java/org/mvndaemon/mvnd/it/DaemonCrashTest.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/MultiModuleTest.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/SingleModuleNativeIT.java
Got uncommitted files after build, without touching anything. Suppose this is a leftover from https://github.com/mvndaemon/mvnd/commit/0f438bdb09df11fc86be93a5e89ee26dc0b21b8b
> Fix TestUtils imports

- client/src/main/java/org/mvndaemon/mvnd/client/DaemonClientConnection.java
- client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
- client/src/main/java/org/mvndaemon/mvnd/client/DaemonDiagnostics.java
- client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
- client/src/test/java/org/mvndaemon/mvnd/client/DaemonConnectorTest.java
- common/src/main/java/org/mvndaemon/mvnd/common/DaemonCompatibilitySpec.java
- common/src/main/java/org/mvndaemon/mvnd/common/DaemonInfo.java
- common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
- common/src/main/java/org/mvndaemon/mvnd/common/DaemonStopEvent.java
- common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
- common/src/main/java/org/mvndaemon/mvnd/common/logging/ClientOutput.java
- common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
- common/src/test/java/org/mvndaemon/mvnd/common/DaemonRegistryTest.java
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
- daemon/src/main/java/org/mvndaemon/mvnd/daemon/DaemonExpiration.java
- daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/assertj/TestClientOutput.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/ExtensionsNativeIT.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/NewManagedModuleNativeIT.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/StopStatusTest.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/UpgradesInBomNativeIT.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/junit/TestRegistry.java
> Fixup 143f4f13 Display the daemon id and shorten it a bit

- common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
> NPE after pressing CTRL+B in the client #324

- README.adoc
> README: Mention --help in 'specific options'

- README.adoc
Added Known issues and limitations section.
Added limitations on using -rf maven option.
> Added known limitations to use -rf maven option

- daemon/src/main/java/org/mvndaemon/mvnd/cache/invalidating/InvalidatingPluginArtifactsCache.java
fix NPE from InvalidatingPluginArtifactsCache similar to #347
> NPE from InvalidatingPluginArtifactsCache, similar to #347

- README.adoc
Add "Install using Chocolatey" section.
> README.adoc: add Chocolatey installation option

- pom.xml
Build locally according to guideline and tested with a local project. OS is Linux.
Is this already enough to verify this is working?
closes #393
> #393 update Maven version to 3.8.1

- README.adoc
- dist/src/main/distro/conf/mvnd.properties
Add some more details on how to set properties for mvnd configuration requested in #383
> Global mvn settings.xml via mvnd.properties #383

- pom.xml
Signed-off-by: Robert Klaus <robert.klaus@posteo.net>
closes #457
> #457 Support Maven 3.8.2

- common/src/main/java/org/mvndaemon/mvnd/common/Message.java
- common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
- daemon/src/main/java/org/mvndaemon/mvnd/builder/SmartBuilder.java
- daemon/src/main/java/org/mvndaemon/mvnd/daemon/ClientDispatcher.java
- daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/BuildEventListener.java
- daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/LoggingExecutionListener.java
Also fix ordering of messages when projects are skipped at the end
> Provide an early display of build failures, fixes #361

- pom.xml
This reverts commit fab202c5f97bcb71a4e5734262eca62395534a73.
> Revert "#457 Support Maven 3.8.2"

- pom.xml
For release 1.0.19.
For list of changes refer to commit (mvnd used 1.0.15):
https://github.com/jvanzyl/provisio/commits/master
> Update Provisio plugin

- client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
- client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
Files.newDirectoryStream  Files.lines and Files.list should be used in try for close
> fix stream leak

- .mvn/wrapper/maven-wrapper.properties
see https://maven.apache.org/docs/3.8.4/release-notes.html
I had no specific reason, was just looking around.
> updates maven from 3.6.3 to 3.8.4

- README.adoc
Hey @ppalaga, a small README addition for manual install on macOS.
> Adding note on removing quarantine flag on macOS

- README.adoc
- RELEASING.adoc
- build/publish-on-sdkman.sh
- build/release.sh
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
- daemon/src/main/java/org/mvndaemon/mvnd/plugin/CliMavenPluginManager.java
- integration-tests/src/test/java/org/mvndaemon/mvnd/junit/MvndTestExtension.java
As the repository is now hosted under `github.com/apache/maven-mvnd`.
> Replace `github.com/mvndaemon/mvnd` references

- src/main/assembly/src.xml
fixes issue found during 0.8.0 vote
> don't skip build/ in source archive

- client/pom.xml
- common/pom.xml
- daemon/pom.xml
- pom.xml
This is a replacement for #635
> Use sisu apt processor

- pom.xml
> Update to Maven 3.8.6 #660

- common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
> Fix for JUnit test failing on Windows

- client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
Fix minor typo in javaHomeFromPath warn log
> fix(log-typo): Fix minor typo in javaHomeFromPath warn log

- daemon/pom.xml
- pom.xml
Depends on https://github.com/takari/takari-smart-builder/pull/25
> Upgrade to takari-smart-builder 0.6.3 (fixes #841)

- build-plugin/src/main/java/org/mvndaemon/mvnd/plugin/doc/DocMojo.java
- native/src/main/java/org/mvndaemon/mvnd/nativ/MvndNativeLoader.java
- native/src/main/java/org/mvndaemon/mvnd/nativ/OSInfo.java
Use this link to re-run the recipe: https://app.moderne.io/recipes/builder/SEvWu02zw?organizationId=QXBhY2hlIE1hdmVu
@elharo and another small one for https://issues.apache.org/jira/browse/MNG-6847
> [MNG-6847] Use diamond operator

- daemon-m39/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
As comments are supported for both 3 and 4 but mvnd did not support them in 3.
Fixes #913 
Fixes #914
> Maven DaemonCLI for 3 and 4 were not aligned

- .github/workflows/release.yaml
Prevent conflicts among uploaded artifacts.
> Fix the release.yaml workflow

- client/pom.xml
Using "compatibility" march.
Fixes #1029
> Lower CPU requirements

- client/pom.xml
Using "compatibility" march.
Fixes #1029
> Lower CPU requirement

- pom.xml
> Use Maven 3.9.9

- pom.xml
Sorting out last bit before doing 1.0.2
> [1.x] Bulk update and some comments

- pom.xml
Changes:
* svm (and enforcer fix)
> Update GraalVM svm to 24.0.2 and fix enforcer

- README.adoc
- client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
- common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenParser.java
- daemon/src/main/java/org/mvndaemon/mvnd/cli/EnvHelper.java
- dist/src/main/distro/conf/mvnd.properties
- integration-tests/src/test/java/org/mvndaemon/mvnd/it/ExtensionsNativeIT.java
Fix https://github.com/apache/maven-mvnd/issues/1163
> Support core extension more configuration

- .github/workflows/pr-automation.yml
https://github.com/apache/maven-gh-actions-shared#pull-request-automation
> Add PR Automation action

- .mvn/maven.config
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCling.java
- daemon/src/main/java/org/apache/maven/cli/DaemonMavenInvoker.java
- pom.xml
Changes:
* use staged Maven 4 rc4
* bring over maven-cli "unfurl" changes
* Maven 3.9.10
* slf4j 2.0.17
* plexus-xml 4.1.0
* junit (from parent) upped to latest 5.13.1
> Upgrade to Maven 4.0.0-rc-4

- common/src/main/java/org/mvndaemon/mvnd/common/OsUtils.java
This PR enhances the Windows RSS memory retrieval functionality in `OsUtils` to provide better compatibility and reliability across different Windows versions.
The current Windows RSS memory retrieval implementation has limited compatibility and can fail on different Windows versions or configurations, leading to unreliable memory monitoring for the Maven daemon.
Implemented a robust multi-layered fallback strategy with three different approaches:
- **Target**: Modern Windows systems (Windows 7+ with PowerShell 2.0+)
- **Method**: Uses `Get-Process -Id <pid>` with `WorkingSet64` property
- **Advantages**: Most accurate, returns precise 64-bit memory values
- **Error handling**: Includes try-catch in PowerShell script to handle process not found
- **Target**: Older Windows systems or when …
> Improve Windows RSS memory retrieval with multiple fallback strategies

- daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
No amount of work changes (all this happened before, but in default ctor). But make it happen lazily.
The pro is that now we have access to all user options, like settings as well (and settings is discriminating).
mvnd 2.x is NOT affected by this, only 1.x.
Fixes #1174
> Lazy daemon
