apache/maven-mvnd

.github/workflows/verify.yaml
client/src/main/java/org/jboss/fuse/mvnd/client/ClientLayout.java
client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
client/src/main/java/org/jboss/fuse/mvnd/client/Environment.java
daemon/pom.xml
daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon/src/main/java/org/jboss/fuse/mvnd/plugin/CliPluginRealmCache.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/ModuleAndPluginNativeIT.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/ModuleAndPluginTest.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/MvndTestExtension.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/TestLayout.java
integration-tests/src/test/projects/module-and-plugin/hello/pom.xml
integration-tests/src/test/projects/module-and-plugin/hello/src/main/java/org/jboss/fuse/mvnd/test/multi/module/hello/Hello.java
integration-tests/src/test/projects/module-and-plugin/hello/src/test/java/org/jboss/fuse/mvnd/test/multi/module/hello/HelloTest.java
integration-tests/src/test/projects/module-and-plugin/plugin/pom.xml
integration-tests/src/test/projects/module-and-plugin/plugin/src/main/java/org/jboss/fuse/mvnd/test/module/plugin/mojo/HelloMojo.java
integration-tests/src/test/projects/module-and-plugin/pom.xml

Fix #33 Maven mojo change ignored

---

client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
client/src/main/java/org/jboss/fuse/mvnd/client/Environment.java
daemon/src/main/java/org/jboss/fuse/mvnd/plugin/CliPluginRealmCache.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/VersionNativeIT.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/VersionTest.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/MvndTestExtension.java

Fix #42 mvnd fails if there is no .mvn/ dir in the user home

---

.github/workflows/verify.yaml

by not installing Visual Studio 2017

Use Visual Studio 2019 pre-installed on Windows CI workers to save some

---

client/src/main/java/org/jboss/fuse/mvnd/client/ClientOutput.java
client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
common/pom.xml
common/src/main/java/org/jboss/fuse/mvnd/common/Message.java
daemon/src/main/java/org/jboss/fuse/mvnd/daemon/Server.java
daemon/src/main/java/org/jboss/fuse/mvnd/logging/smart/AbstractLoggingSpy.java
daemon/src/main/java/org/jboss/fuse/mvnd/logging/smart/MavenLoggingSpy.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/assertj/MatchInOrderAmongOthers.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/MultiModuleTest.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/SingleModuleNativeIT.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/StopStatusTest.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/VersionNativeIT.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/junit/NativeTestClient.java

All events are directly forwarded to the client.  The client is now responsible for ordering them per project and displaying them if needed.  A thread is now started to read the terminal input with support for '+' to display one more line per project, '-' to display one line less, and 'Ctrl+L' to redraw the display which could become messed if the build messages are a bit unusual (this may require a better fix though).

Provide smarter output on the client, fixes #77

---

client/src/main/java/org/jboss/fuse/mvnd/client/DaemonConnector.java
client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
common/src/main/java/org/jboss/fuse/mvnd/common/logging/ClientOutput.java
common/src/main/java/org/jboss/fuse/mvnd/common/logging/TerminalOutput.java
daemon/src/main/java/org/jboss/fuse/mvnd/plugin/CliPluginRealmCache.java

* Say 'Looking for daemon...' straight ahead to elliminate the initial lag
* Present 'hidden' threads along with used/max threads instead of 'n more'
* Print project name in bold even if no mojo is present in the line
* Be consistent about printing project artifactIds in bold also when lines are hidden
* The rich status line is present also when lines are hidden

Improve terminal output

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java

Fix spelling error in console logs

---

client/src/main/java/org/jboss/fuse/mvnd/client/DaemonClientConnection.java
client/src/main/java/org/jboss/fuse/mvnd/client/DefaultClient.java
common/src/main/java/org/jboss/fuse/mvnd/common/Message.java
common/src/main/java/org/jboss/fuse/mvnd/common/logging/ClientOutput.java
common/src/main/java/org/jboss/fuse/mvnd/common/logging/TerminalOutput.java
daemon/src/main/java/org/jboss/fuse/mvnd/builder/ProjectExecutorService.java
daemon/src/main/java/org/jboss/fuse/mvnd/builder/SmartBuilder.java
daemon/src/main/java/org/jboss/fuse/mvnd/builder/SmartBuilderImpl.java
daemon/src/main/java/org/jboss/fuse/mvnd/daemon/Server.java
daemon/src/main/java/org/jboss/fuse/mvnd/logging/smart/MavenLoggingSpy.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/assertj/TestClientOutput.java
integration-tests/src/test/java/org/jboss/fuse/mvnd/it/InteractiveTest.java

Implement build cancelation

---

client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java

@gnodet I must say I do not like how rollingWindowSize defaulting to 2 looks on my machine with many processors. I propose to keep the default at 0 for now and discuss in a new issue how we will proceed. I have a couple of ideas how it could work.

Make TerminalOutput.dumb final, activate TerminalOutput.noBuffering with -B/--batch-mode, mvnd.rollingWindowSize default 0

---

client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
client/src/main/java/org/mvndaemon/mvnd/client/ExecutionResult.java
common/src/main/java/org/mvndaemon/mvnd/common/Message.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/NewManagedModuleNativeIT.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/NewManagedModuleTest.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/UpgradesInBomNativeIT.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/JvmTestClient.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/MvndTestExtension.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/NativeTestClient.java
integration-tests/src/test/projects/new-managed-module/changes/bom/pom.xml
integration-tests/src/test/projects/new-managed-module/changes/module/pom.xml
integration-tests/src/test/projects/new-managed-module/changes/module/src/main/java/org/mvndaemon/mvnd/test/upgrades/bom/module/UseHello.java
integration-tests/src/test/projects/new-managed-module/changes/new-module/pom.xml
integration-tests/src/test/projects/new-managed-module/changes/new-module/src/main/java/org/mvndaemon/mvnd/test/upgrades/nw/module/Hello.java
integration-tests/src/test/projects/new-managed-module/changes/pom.xml
integration-tests/src/test/projects/new-managed-module/parent/bom/pom.xml
integration-tests/src/test/projects/new-managed-module/parent/module/pom.xml
integration-tests/src/test/projects/new-managed-module/parent/module/src/main/java/org/mvndaemon/mvnd/test/upgrades/bom/module/UseHello.java
integration-tests/src/test/projects/new-managed-module/parent/pom.xml

Exit code not propagated from the daemon to mvnd client

---

build-plugin/pom.xml
build-plugin/src/main/java/org/mvndaemon/mvnd/plugin/doc/DocMojo.java
client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
client/src/main/java/org/mvndaemon/mvnd/client/DaemonDiagnostics.java
client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
common/pom.xml
common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
common/src/main/java/org/mvndaemon/mvnd/common/OptionType.java
daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon/src/main/java/org/apache/maven/cli/MvndHelpFormatter.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/AbstractLoggingSpy.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/LoggingExecutionListener.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/MvndTestExtension.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/NativeTestClient.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/TestRegistry.java
integration-tests/src/test/projects/daemon-crash/.mvn/maven.config
integration-tests/src/test/projects/extensions/.mvn/maven.config
integration-tests/src/test/projects/invoker/.mvn/maven.config
integration-tests/src/test/projects/module-and-plugin/.mvn/maven.config
integration-tests/src/test/projects/multi-module/.mvn/maven.config
integration-tests/src/test/projects/new-managed-module/.mvn/maven.config
integration-tests/src/test/projects/single-module/.mvn/maven.config
integration-tests/src/test/projects/upgrades-in-bom/.mvn/maven.config
pom.xml

Let -h/--help display also mvnd specific options #243

---

common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
common/src/main/java/org/mvndaemon/mvnd/common/OptionType.java
daemon/src/main/java/org/apache/maven/cli/MvndHelpFormatter.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/TestRegistry.java

Document --status, --stop and --purge in -h/--help 

---

common/src/main/java/org/mvndaemon/mvnd/common/Environment.java

The boolean type cause the following argument to be swallowed

Fix SERIAL command line option

---

client/pom.xml
client/src/main/java/org/mvndaemon/mvnd/client/Completion.java
client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
client/src/main/resources/mvnd-bash-completion.bash
client/src/test/java/org/mvndaemon/mvnd/client/CompletionGenerator.java
client/src/test/resources/completion-templates/mvnd-bash-completion.bash
common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
common/src/main/java/org/mvndaemon/mvnd/common/IoUtils.java
common/src/test/java/org/mvndaemon/mvnd/common/DaemonRegistryTest.java
daemon/src/main/java/org/apache/maven/cli/MvndHelpFormatter.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/CompletionNativeIT.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/CompletionTest.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/TestRegistry.java
pom.xml

Bash completion 

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

A new daemon is always started on Java 8 

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java

@gnodet this should be a pure refactoring with no changes of behavior. The main intention is to make the code easier to read and easier to reason about.

Less global and mutable state

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/AbstractLoggingSpy.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/LoggingExecutionListener.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/ProjectBuildLogAppender.java
dist/src/main/distro/conf/logback.xml

This is the second commit from https://github.com/mvndaemon/mvnd/pull/285, simplified and without renaming and moving AbstractLoggingSpy so that it is easier to follow what it does. Could you please review, @gnodet ?

Eliminate mutable global state in AbstractLoggingSpy

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/ClientDispatcher.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/BuildEventListener.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/LoggingExecutionListener.java
daemon/src/main/java/org/mvndaemon/mvnd/logging/smart/ProjectBuildLogAppender.java

The last part of the refactoring originally done in https://github.com/mvndaemon/mvnd/pull/285

Rename AbstractLoggingSpy to ClientDispatcher and move it to org.mvndaemon.mvnd.daemon

---

client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/Message.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/ClientDispatcher.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/MultiModuleTest.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/MvndTestUtil.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/SingleModuleNativeIT.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/SingleModuleTest.java

Fix #288
This PR depends on PR https://github.com/mvndaemon/mvnd/pull/285 , but the idea in itself is independent. In case you veto #285 @gnodet , I can rebase this. 
Once again, this is how it looks like:

Right-pad projectIds to improve mojo readability in the threaded view 

---

README.adoc
client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/Environment.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
daemon/src/test/java/org/mvndaemon/mvnd/cache/impl/CacheFactoryTest.java
daemon/src/test/java/org/mvndaemon/mvnd/daemon/ServerTest.java
dist/src/main/distro/bin/mvnd-bash-completion.bash
integration-tests/pom.xml
integration-tests/src/test/java/org/mvndaemon/mvnd/it/EnvironmentTest.java

Leverage Maven's -Dstyle.color to avoid coloring instead of stripping the ASCII codes in the client

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
common/src/main/java/org/mvndaemon/mvnd/common/DaemonInfo.java
common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
common/src/test/java/org/mvndaemon/mvnd/common/DaemonRegistryTest.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

Adds a token to the persisted daemon registry, which the client is required to transmit directly after initiating the connection with the daemon.

#390 Restrict usage of mvnd daemons to the current user by utilizing a token check

---

common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
common/src/test/java/org/mvndaemon/mvnd/common/DaemonRegistryTest.java

Fix a possible write a long string in case where the string length is <= 1024 but the encoded size if > 1024.
Truncate long strings and warn instead of throwing an exception which could lead to an invalid registry.
Since the registry data is invalid, the content is emptied to guarantee the next registry will work correct.
This fix is based on #435 provided by @lanmaoxinqing, many thanks !

Attempt to fix bad registry errors, fixes #432 and #433

---

daemon/src/main/java/org/mvndaemon/mvnd/timing/BuildTimeEventSpy.java

The build time event spy should aggregate values for each mojo #430

---

README.adoc

I've just added a port for `mvnd` to MacPorts: https://ports.macports.org/port/mvnd/
This merge request adds the command for installing `mvnd` via MacPorts to the readme.

Add instructions for MacPorts

---

client/src/main/java/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/MavenDaemon.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

This fixes a few things:
* the clearCache was not working because the reflection access was forbidden, this may fix a bunch of problem on windows and the clearCache should be called after a maven execution, not only when the daemon is closed  could that fix https://github.com/mvndaemon/mvnd/issues/115 ?)
* revert the url cache to its default value (should fix https://github.com/mvndaemon/mvnd/issues/527)

Fix url cache

---

README.adoc

The change fixes link to the GraalVM's native-image documentation that has been changed.

Fixes url for GraalVM's native-image prerequisites

---

pom.xml

Even if the attack vector for the [CVE-2021-42550](https://nvd.nist.gov/vuln/detail/CVE-2021-42550) is very limited in mvnd, I think it's worth to have the newest version of logback.

Upgrades logback to the newest version to fix CVE-2021-42550

---

.github/dependabot.yml

Regarding recent supply chain attacks having a decent mechanism to easily integrate updates seems to me very important.
This adds github own mechanism. An alternative would be whitesource.

introduce dependabot

---

pom.xml

2022-01-13 - Release of SLF4J 1.7.33
• SLF4J now ships with the slf4j-reload4j module delegating to the reload4j backend. Reload4j is a drop-in replacement for log4j version 1.2.17.
• SimpleLogger now prints the thread Id if instructed to do so. This fixes SLF4J-499 requested by Michael Osipov

Upgrade SLF4J to version 1.7.35

---

daemon/src/main/java/org/mvndaemon/mvnd/logging/internal/MvndSlf4jConfiguration.java

The maven invoker uses debug output by default when running integration tests.
However, mvnd does not support the '-X' flag in this case.

Fix mvn/bin/mvn debug output

---

common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java

Fixes #608. Tested with Java 11 in non-native mode (from `./dist/target/mvnd-0.7.2-SNAPSHOT-linux-amd64/bin/`) on Linux and Windows 10.

Make `DaemonRegistry.getProcessId0` more robust

---

common/pom.xml
daemon/pom.xml
native/pom.xml
pom.xml

not sure this is sufficient, but at least this is required for Reproducible Builds...

prepare Reproducible Builds

---

build/publish.sh

ASF does not need md5 nor sha1 nor sha256: only .asc and .sha512

only publish sha256, skip md5+sha1+sha512

---

.github/workflows/release.yaml
src/main/assembly/src.xml

without these, you can't immediately build as you do from Git checkout

Configure execution bit for required scripts in source distribution

---

common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java

The module id coloring was not consistent during transfer and it caused "vibrating" effect.
https://github.com/apache/maven-mvnd/issues/685

Fixes module id coloring on Maven transfer.

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
client/pom.xml
pom.xml

Apple Silicon is only supported since 22.1.0 https://www.graalvm.org/release-notes/22_1/#platform-updates so an upgrade to 22.x is necessary to build Mac AArch64 binaries.

Update GraalVM to 22.2.0

---

common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java

In case of an error, the read lock is never released which would prevent subsequent write locks.
* Release the read lock in a finally block to ensure that it will be released in any case.

Release the read lock in a finally block

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
common/src/main/java/org/mvndaemon/mvnd/common/OsUtils.java

Calculate java home from java command

---

dist/src/main/distro/bin/mvnd.cmd
dist/src/main/distro/bin/mvnd.sh
dist/src/main/distro/mvn/bin/mvn
dist/src/main/distro/mvn/bin/mvn.cmd

The main change of the upstream scripts is removing the dependency of `which` command. This improve the portability.

Sync entry scripts with maven 3.8.6

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java

Event spies may want to read system properties, which will fail if they are reset too early. This change makes the behavior consistent with regular Maven.

Reset system properties after calling event syps

---

common/src/main/java/org/mvndaemon/mvnd/common/Environment.java

The local repo and maven settings are both used while resolving core extensions, which happens during daemon startup. Thus these two also need to be discriminating properties, as the core extensions themselves are discriminating.
Our concrete use case is that our extension's integration tests use an isolated repository which is deleted after the build, so we don't pile up garbage data on our CI agents. The lack of support for a custom local repository means we currently can't run the tests for our Maven extension against the Maven daemon.

Add more discriminating properties to the daemon

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
client/pom.xml

This pr improves native image portability on linux and windows via:
1. Enable mostly static image switch on linux and windows. on linux, the cost is about 33K file size before compressed, about +0.1%.
2. Loose linux `glibc` requirement to 2.12. Now the `mvnd` depends on many `JNI`s which are built by `glibc` toolchains, so we cannot easily switch to `musl` toolchains or a fully static image (discussed in #727 ). Whereas a lower glibc requirement adds support for most old linux boxes.
An explicit `glibc` requirement also removes a side effect of changing the build system. When update the build system from ubuntu 18.04 to 20.04, the glibc requirement may also increase to match the new os. On the other hand, glibc 2.12 is required by graalvm.

Build mostly static native image, loose linux glibc requirement to 2.12

---

common/src/main/java/org/mvndaemon/mvnd/common/Message.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

The implementation currently switches on the redirection when the daemon actually starts reading the System.in stream using InputStream.read() or InputStream.available().

Support redirecting input from client to daemon, #541

---

common/src/main/java/org/mvndaemon/mvnd/common/SignalHelper.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

This opens some room to per-jdk implementation

Move signal handling into its own class

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/ExtensionWithApiTest.java
integration-tests/src/test/projects/extension-with-api/.mvn/extensions.xml
integration-tests/src/test/projects/extension-with-api/.mvn/maven.config
integration-tests/src/test/projects/extension-with-api/extension/.mvn/maven.config
integration-tests/src/test/projects/extension-with-api/extension/pom.xml
integration-tests/src/test/projects/extension-with-api/extension/src/main/java/org/mvndaemon/mvnd/test/extension/with/api/extension/TheApi.java
integration-tests/src/test/projects/extension-with-api/extension/src/main/java/org/mvndaemon/mvnd/test/extension/with/api/extension/TheImpl.java
integration-tests/src/test/projects/extension-with-api/extension/src/main/resources/META-INF/maven/extension.xml
integration-tests/src/test/projects/extension-with-api/plugin/.mvn/maven.config
integration-tests/src/test/projects/extension-with-api/plugin/pom.xml
integration-tests/src/test/projects/extension-with-api/plugin/src/main/java/org/mvndaemon/mvnd/test/extension/with/api/plugin/TheMojo.java
integration-tests/src/test/projects/extension-with-api/pom.xml

Since https://github.com/apache/maven/pull/616, the default CoreExportProvider no longer uses the provided CoreExports, but instead tries (and fails) to discover them itself.
This change fixes that by providing our own custom instance of CoreExportProvider. This allows core extension to contribute exported artifacts and exported packages again, like it used to do before the Maven 4.x upgrade.

Fix core export provider

---

.github/workflows/early-access.yaml

Already fixed on master, cherry-picked from 5cd0f754d58ec213d19e5e95f40ac15ec4f36e05

[0.10.x] Publish the binaries produced by the Early Access job again

---

.github/workflows/early-access.yaml
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

* similar fix is likely needed for master branch, possible older branches (but the issue is not manifesting in daemon 0.9.x so maybe we don't need to backport there)

[0.10.x] Run client connection handler inside new thread, fixes #798

---

.github/workflows/early-access.yaml
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

* same as https://github.com/apache/maven-mvnd/pull/799 but for master branch
* I quickly tested this locally and master was suffering from the same thread leak issue as the 0.10.x. If we decided this is the solution, then it should be applied to master as well

Run client connection handler inside new thread, fixes #798 

---

.github/workflows/early-access.yaml
integration-tests/src/test/java/org/mvndaemon/mvnd/it/ExtensionWithApiNativeIT.java

* `mvn clean install` currently fails with
```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR] org.mvndaemon.mvnd.it.ExtensionWithApiTest.pluginCanAccessExtensionApi
[ERROR]   Run 1: ExtensionWithApiTest.pluginCanAccessExtensionApi » IllegalState mvnd executable does not exist: <...>/maven-mvnd/dist-m39/target/maven-1.0.0-m5-SNAPSHOT-mvnd-m39-linux-amd64/bin/mvnd
[ERROR]   Run 2: ExtensionWithApiTest.pluginCanAccessExtensionApi » IllegalState mvnd executable does not exist: <...>/maven-mvnd/dist-m39/target/maven-1.0.0-m5-SNAPSHOT-mvnd-m39-linux-amd64/bin/mvnd
[ERROR]   Run 3: ExtensionWithApiTest.pluginCanAccessExtensionApi » IllegalState mvnd executable does not exist: <...>/maven-mvnd/dist-m39/target/maven-1.0.0-m5-SNAPSHOT-mvnd-m39-linux-amd64/bin/mvnd
[ERROR]   Run 4: …
```

Make the default (non-native) build work again

---

client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
common/src/main/java/org/mvndaemon/mvnd/common/DaemonConnection.java
common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
common/src/main/java/org/mvndaemon/mvnd/common/OsUtils.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
common/src/test/java/org/mvndaemon/mvnd/common/OsUtilsTest.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java
daemon/src/main/java/org/mvndaemon/mvnd/interactivity/DaemonPrompter.java

When browsing through the code I encountered some small things which I think makes sense to fix, so I figured I would create a PR. 
I may possibly create more of these if I encounter similar things elsewhere in the code -- and of course if PRs likes are something you are interested in (as I know reviewing things like this is not super exciting)

Random minor fixes / clean-up in OsUtils

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml

* currently used versions are deprecated and GitHub is printing warnings on the actions page, e.g. "Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2."
* I am not really able to test the changes in the `release` workflow, but the changes looks safe enough

Bump GitHub actions version

---

common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
dist/src/main/distro/mvn/conf/logging/logback-daemon.xml

Also make sure the daemon prompter log only goes to the daemon log

Prompter prompt should not prepend the projectId when there's only one project, fixes #816

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml

* fixes #812 
* building on ubuntu:22.04 produces binaries which require too recent glibc
version (2.32+) and that means the binary no longer works on
older ubuntu versions, like 20.04 and 18.04.
* building on ubuntu:20.04 fixes the problem and the binary again works
on ubuntu 18.04 and 20.04
* also bumped the version in the release workflow which got forgotten

Build on ubuntu 20.04

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
client/pom.xml
client/src/main/resources/glibc/dynamic-libc-start.c
client/src/main/resources/glibc/gcc
client/src/main/resources/glibc/glibc.redef
native/pom.xml
pom.xml

Make native mvnd only require glibc 2.12 on ubuntu 22.04

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java
daemon-m39/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon-m39/src/main/java/org/mvndaemon/mvnd/execution/DefaultBuildResumptionDataRepository.java
daemon-m40/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon/src/main/java/org/mvndaemon/mvnd/interactivity/DaemonPrompter.java
daemon/src/main/java/org/mvndaemon/mvnd/timing/BuildTimeEventSpy.java

See also:
* https://github.com/apache/maven/pull/1080
* https://github.com/apache/maven-resolver/pull/275
This PR along with https://github.com/apache/maven-resolver/pull/275 get rid of commons-lang3 from the maven distribution, saving 500k on disk.

[MNG-6825] Remove plexus-utils and commons-xxx references

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
client/src/main/resources/glibc/dynamic-libc-start.c

Workround of return-to-csu problem for old glibc, use non-initialized static variables instead of the stack ones. See workround 2 of https://i.blackhat.com/briefings/asia/2018/asia-18-Marco-return-to-csu-a-new-method-to-bypass-the-64-bit-Linux-ASLR-wp.pdf

native image: hardening csu for old glibc

---

daemon-m39/src/main/java/org/mvndaemon/mvnd/cache/invalidating/InvalidatingPluginDescriptorCache.java
daemon-m40/src/main/java/org/mvndaemon/mvnd/cache/invalidating/InvalidatingPluginDescriptorCache.java

The second get-method wasn't actually overloaded, but had a different signature than the superclass. This resulted in the superclass cache being filled and never cleared, even when flush is called.

Fix PluginDescriptorCache

---

README.adoc

I would like to propose adding the following details to the instructions for building `maven-mvnd` on Windows.
I had to spend some time figuring out which tools I needed and I figured I would save other future Windows contributors the trouble.

Update build instructions for Windows

---

.github/dependabot.yml
common/pom.xml
daemon-m39/pom.xml
daemon-m40/pom.xml
daemon/pom.xml
logging/pom.xml
pom.xml

Changes:
* parent POM 42
* unset release where needed (makes com.sun pkg unreachable)
* explicitly index as parent disables "implicit" AP
* remove redundtant stuff
* update dependabot to take care of workflow as well (as mvnd uses own)

Update to parent POM 42

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
client/src/main/resources/glibc/glibc.redef

Instead to do this one-by-one as pushed by dependendabot...

Cumulative update of GH flow

---

daemon-m39/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
integration-tests/src/test/projects/maven-conf/.mvn/maven.config

Port Maven 3.9.6 config and new properties (session.root/top) interpolation into Daemon m39.
The IT got this property as it triggers exception (failure) if mvn39 could not "discover" top directory.
Fixes #910

Align mvnd m39 with Maven 3.9.x re config interpolation

---

daemon-m39/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
daemon-m40/src/main/java/org/apache/maven/cli/DaemonMavenCli.java

The "happy path" should happen without anything thrown, unsure why here runtime ex is rethrown, others swallowed.
Change: just remove the try/catch and make method throw Exception (diff best seen with whitespace ignored).
Fixes #957
Fixes #966

Daemons should not swallow any exception

---

common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java

Mitigates #929 but does not have an ambition to find the root cause.

Make TerminalOutput.pathToMaven() more robust to avoid #929

---

.mvn/wrapper/maven-wrapper.properties
daemon/src/main/java/org/apache/maven/cli/DaemonMavenCli.java
logging/pom.xml
mvnw
mvnw.cmd
pom.xml

And fix the build w/ smaller cleanups, plugin updates and backport of `-itr`, `-sadp`.
Changes:
* Maven 4 beta-2 (staged, on vote)
* Maven Wrapper 3.3.1 + script updates
* maven-plugin-tools 3.13.0
* buildhelper-maven-plugin 3.6.0
* graalvm plugin 0.10.2
* provisio 1.0.25
* exec-maven-plugin 3.3.0
* backport `-itr` and `-sadp` (Maven CLI)

Maven 4 beta-2

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonParameters.java

Default must be manually handled, i missed this.
Fixes #912
Backport of #953 to mvnd-1.x

Backport of "Default value must be handled"

---

.mvn/wrapper/maven-wrapper.properties
build-plugin/pom.xml
common/pom.xml
common/src/main/java/org/mvndaemon/mvnd/common/InterpolationHelper.java
common/src/main/java/org/mvndaemon/mvnd/common/OsUtils.java
daemon/pom.xml
integration-tests/pom.xml
logging/pom.xml
mvnw
mvnw.cmd
native/pom.xml
pom.xml

Changes:
* no source changes
* (build) expel all versions from child modules: they must be all top level depMgmt or pluginMgmt
* (build) Top POM contains GAVs while child modules GA+scope. This tremendously simplifies maintenance.
* (javadoc) fix Javadoc errors
Updates:
* use latest Maven 3.9.8-SNAPSHOT (TS locked version, controlled deploy by me)
* AssertJ 3.26.0
* Takari Smart Builder 0.6.6
* Sisu 0.9.0.M3
* maven wrapper 3.3.2 w/ scripts
This brings mvnd-1.x in "releasable" state (once Maven 3.9.8 is out).

[1.x] Pre-release tidy-up

---

.github/workflows/early-access.yaml
.github/workflows/release.yaml
.mvn/release-settings.xml
pom.xml

GH Action and related changes to finally cover all targeted OS/platforms with native binary.
Changes:
* no source change
* POM change: using released Maven 3.9.8 (and added access to staged Maven 3.9.8)
* Provide 4 plaf binaries: linux amd64, windows amd64, mac amd64 and mac aarch64
* adopt GH workflows for these changes (using "OS" alone is not enough)
* adopt generally GraalVM naming and use them consecutively

Release binaries: linux amd64, macos amd64, macos aarch64, windows amd64

---

client/pom.xml
client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
common/pom.xml
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
dist/src/main/provisio/maven-distro.xml
pom.xml

And use JNI (and FFM) instead.
Changes:
* use DefaultClient from master (thanks @gnodet !)
* drop jansi (as DefaultClient should not depend on it)
* introduce two new jline3 terminal backends: jni and ffm (used on Java 22+)
* tested/verified (thanks @wendigo )

Fix deprecation warning about JAnsi Terminal

---

integration-tests/src/test/projects/type-description/pom.xml
integration-tests/src/test/projects/type-description/server/src/main/java/org/mvndaemon/mvnd/test/type/description/server/domain/AbstractEntity.java
integration-tests/src/test/projects/type-description/server/src/main/java/org/mvndaemon/mvnd/test/type/description/server/domain/Image.java

So far it was buildable ONLY with Java 17, but only due single IT: it used old Quarkus version that refused to work on Java 21. Ported updates from mvnd master and now mvnd-1.x branch can also be build without any problem with Java 21.

Make mvnd-1.x buildable with Java 21

---

.github/workflows/release.yaml
build/release-build.sh

Changes:
* `release-build.sh`: Just do not push. This allows one to locally verify the outcome, and push (for now manually like `git push origin mvnd-1.x --tags`). Added reminder message.
* `release.yaml`: whenever mvn would resolve deps, make sure release settings XML is present. It does not stir anything if Maven is in Central, but as in this moment, maven is still staged only.

More script changes

---

build/release-candidate.sh

Fix release candidate script

---

README.adoc

As a first-time user of the Maven Daemon, I was reading the README to make sure I apply everything that is relevant in my context.
I was curious about the note to the `oh-my-zsh` users, about a previous incompatibility between `mvnd` and the alias of the `mvn deploy` used by the `omz` maven plugin.
On a second look, it seems that the incompatibility has been resolved because `oh-my-zsh` has renamed `mvnd` to `mvndp` to resolve this particular problem.
Please check the relevant commit: https://github.com/ohmyzsh/ohmyzsh/pull/11756
and the linked issue: https://github.com/ohmyzsh/ohmyzsh/issues/11713
The up-to-date `omz maven plugin` documentation reflects the change: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/mvn
| Alias                | Command …

Remove outdated note about oh-my-zsh

---

client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/Message.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
integration-tests/src/test/java/org/mvndaemon/mvnd/assertj/TestClientOutput.java

ProjectEvent message mixup fixed.
Fixes #1036

[1.x] mixup in case of DISPLAY messages type

---

client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
common/src/main/java/org/mvndaemon/mvnd/common/Message.java
common/src/main/java/org/mvndaemon/mvnd/common/logging/TerminalOutput.java
integration-tests/src/test/java/org/mvndaemon/mvnd/assertj/TestClientOutput.java

ProjectEvent message mixup fixed.
Fixes #1036

mixup in case of DISPLAY messages type

---

README.adoc

Document how to install the [mvnd port](https://ports.macports.org/port/mvnd/) from MacPorts. (I'm the maintainer of the port.)

Document installation instructions for MacPorts

---

logging/src/main/java/org/mvndaemon/mvnd/logging/slf4j/MvndSimpleLogger.java

This was a small discrepancy to the output of vanilla Maven and made the output
hard to read, since the failure class name started right after the message without
any whitespace in between.

Separate message and exception by newline

---

logging/src/main/java/org/slf4j/impl/MvndSimpleLogger.java

This was a small discrepancy to the output of vanilla Maven and made the output hard to read, since the failure class name started right after the message without any whitespace in between.

[1.x] Separate message and exception by newline

---

daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

We have a test suite for a Maven extension that runs around 5000 builds and before this change, on each CI build, about 100 of them would fail with daemon connection issues. The symptom would always be the same - The daemon is waiting for the build request, the client has already sent it, but the daemon never receives it, no matter how long we configured the timeouts. 
The reason turned out to be the way that the daemon waits for the request:
The Server was using a SynchrnousQueue to coordinate the main thread
and the background thread that receives the request from the client.
A SynchronousQueue only allows insertions when a corresponding call
to `get` is in progress. However, since the receiver thread is started
before the call to `get`, there was a short time window, where the call
to …

Fix daemon connection issues

---

build/publish-on-sdkman.sh

mvnd on master still produces "betas" (as long as mvn master does), and it must not be set as "default" version in SDKMAN. Defaults are still coming from mvnd-1.x branch.

Fix SDKMAN publish from master

---

README.adoc

Readme cleanup to allow the install commands to be copied and pasted without modification.
This fixes the error:
```
zsh: command not found: $
```

chore: make install commands copy+pastable

---

client/pom.xml
integration-tests/pom.xml
pom.xml

The plugin introduced some "windows fix"[1] that causes current arg parsing to fail. Solution seems to be to split each arg in own line, but that introduced another set of challenges.
[1] https://github.com/graalvm/native-build-tools/pull/609
Supersedes https://github.com/apache/maven-mvnd/pull/1135

Bump native-maven-plugin from 0.10.2 to 0.10.3

---

daemon/src/main/java/org/apache/maven/cli/DaemonMavenParser.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/JvmTestClient.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/NativeTestClient.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/TestUtils.java

Experiment PR to figure out why MacOS GH runners keep failing with transport related (SSL handshake abort, HTTP timeouts) errors. As we know linux and windows boxes are in Azure, while macos boxes are somewhere else, and we get regularly real strange errors like "SSL handshake errors", "HTTP timeout error (against Central?)", so suspicion is on JDK transport (in HTTP/2 mode).
Experiments:
* force apache transport (HTTP/1.1) - :heavy_check_mark: 
* force JDK transport into HTTP/1.1 - :red_square: 
* use big timeout for connectTimeout - :heavy_check_mark: 
Conclusion: for ITs we will for now increase the default (10sec) `connectTimeout` Resolver configuration, as it seems too low.

mvnd IT: increase connectTimeout for ITs

---

daemon/src/main/java/org/apache/maven/cli/DaemonCli.java
daemon/src/main/java/org/apache/maven/cli/DaemonMavenCling.java
daemon/src/main/java/org/apache/maven/cli/DaemonMavenInvoker.java
daemon/src/main/java/org/mvndaemon/mvnd/daemon/Server.java

As long daemon is alive, the daemon invoker must be kept alive as it holds the "resident" object graph of Maven.

fix: Daemon invoker lifespan must be shared with daemon process lifespan

---

common/src/main/java/org/mvndaemon/mvnd/common/DaemonRegistry.java
common/src/test/java/org/mvndaemon/mvnd/common/DaemonRegistryTest.java
common/src/test/java/org/mvndaemon/mvnd/common/RegistryMutator.java

The previous implementation had two issues:
The memory-mapped file was created in the constructor and ignored file expansions by other
threads or processes. It would then overwrite the file with its own, smaller size buffer.
Replaced the memory mapping with a regular InputStream/OutputStream approach. Memory mapping
is not very useful in this scenario anyway, since the file is small and infrequently read and
we always read/write the entire file.
The tryLock method was broken and only tried locking once. If the lock could not be acquired,
it returned null and the subsequent code then ignored that fact and proceeded without locking.
I've moved the retry loop and failure handling into the lock method, which gives it the intended
behavior of waiting for a lock for 20s and then failing.
The …

Make DaemonRegistry concurrency-safe

---

.github/ci-extensions.xml
.github/workflows/early-access.yaml

Use Maveniverse Mimir to cache central artifacts. This makes caching way simpler as well. Update Maven used to build to Maven 4.0.0-rc-3 as well.

[experiment] Mimir

---

integration-tests/src/test/java/org/mvndaemon/mvnd/it/ConcurrentDownloadsTest.java

As due Mimir, it does not download anymore and assertion fails. With Mimir primed caches, everything is got from cache.

Disable ConcurrentDownloadsTest for now

---

.github/ci-mimir-daemon.properties
.github/workflows/early-access.yaml
.mvn/wrapper/maven-wrapper.properties

We don't need it. Config copied from Maven.
For this to work (user wide extension) I upped Maven version to 4.0.0-rc-3 as well, again, same as in Maven CI.

Mimir: make sure JGroups is not running

---

client/pom.xml
client/src/main/resources/org/mvndaemon/mvnd/client/build.properties
pom.xml

Just use Nisse, as it is already in place, plus it does not require git checkout either.
Fixes #1306

Drop buildnumber plugin, Nisse is in place

---

.github/dependabot.yml

- add 'dependencies' label
- check GitHub Action in 1.x

Improve configuration for dependabot in 1.x branch

---

.mvn/maven.config
pom.xml

As Nisse is "drop in replacement" for OS-Detector, but this code was different from start (ie amd64 vs x86_64).

Return gmaven for OS detection

---

dist/src/main/distro/bin/mvnd.cmd

Port from Maven core:
- https://github.com/apache/maven/pull/1808
reference issue: 
- https://issues.apache.org/jira/browse/MNG-8315

[MNG-8315] Fix MAVEN_PROJECTBASEDIR in mvn.cmd when .mvn is at drive root

---

client/src/main/java-mvnd/org/mvndaemon/mvnd/client/DefaultClient.java
integration-tests/src/test/java/org/mvndaemon/mvnd/it/MavenConfIgnoreExtNativeIT.java
integration-tests/src/test/java/org/mvndaemon/mvnd/junit/JvmTestClient.java

The JvmTestClient pushed things to system properties and then did not clean up them. This went invisible, as long as user did not have user-wide extensions like smart-builder that suddenly was not filtered out anymore from tested mvnd daemon and caused havoc.
Changes:
* def client helper method emits "prev state" for properties it altered
* JvmTestClient uses this map to restore properties
* MavenConfIgnore ITs modified to still ignore takari smart builder as well...
Fixes #1357

Fix test framework side effects (java props)

---

client/src/main/java/org/mvndaemon/mvnd/client/DaemonConnector.java
client/src/test/java/org/mvndaemon/mvnd/client/NoDaemonTest.java

Fixes #1248
When running with `mvnd.noDaemon=true`, the `connectNoDaemon()` method was setting up various system properties but missing the crucial `MVND_JAVA_HOME` property. This caused the Server constructor to fail with:
```
java.lang.IllegalStateException: The system property mvnd.java.home is missing
```
The issue was in the `connectNoDaemon()` method in `DaemonConnector.java`. When running with `mvnd.noDaemon=true`, the method sets up properties like:
- `JAVA_HOME` (from `parameters.javaHome()`)
- `USER_DIR`, `USER_HOME`, `MVND_HOME`, etc.
- But it **did NOT set `MVND_JAVA_HOME`**
When the `Server` constructor runs, it tries to access `Environment.MVND_JAVA_HOME.asString()` which throws an `IllegalStateException` if the property is missing.
The fix adds the missing `MVND_JAVA_HOME` …

Fix mvnd.java.home not set in noDaemon mode
